travis:
  secure:
    BINSTAR_TOKEN: gu0E9j4J1GIE2pc+tFjSkAPqvQd1o69JN7auFeuSDCZibwpEJjCXcQLpd/XK1TrB69LY/xWp6i0hboDvx82Q7yK/xmHKvXZ0niahqJae97TTHayqHPohE8Hs6B8jM5vTZvUc0MAKlWz/1aQ7d6KeNBNfNdmiqVdgjc/Nk44fFvmfbGEt0gb0Km4nt2dBfVIOKANuYGKLD7GIfHFRovE4SL8sGFVpPOBvanx6tg072gC+bZ+9oxc9XOkj78uXR1UcrOfuVnhGV+Fqi3iyszgY6kYvQ8We3GiVXQDQve5Yid0IJOTq/gvdLLHkvIOjy7J7IbulRlYUVwGcFJc6L0tpFRLOlB/Q6/7wLkCm2ImMKQRWzvvRAS0j2kb5OwbObyjyjtTpSv+XXwgSPSv9hoSzQRcB9+HfnvaFBlzZXijBwtEEr68kDs0E2TBOMZbnnHgDV62d/Gb8bZtDjPmPUfjy4UjdlXTsi2piNOC18/eyVCzo0wjgwuMzQMxFZvf8Dcr8YhuXrfnWLjzfCbx9PAIiOKqY9XXmUlzh4ghSP/nPJwOPnjfeylk+q/uWGFHRh3Y8S/ZmWaStBk7XyC3vT+Fi4t3pwH3oe4rBRl2K9Yv2+Vf/9knKEUCFp7osxk75jBUd572JVFxH9aBfMoGIsCxxVt7TBHzm4Ja7PNP1C0ghgqw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
