travis:
  secure:
    BINSTAR_TOKEN: M13DI3swtFBFOFED2b9gcXqy57Dd77Oe3KlfbwmvyrIMTwtyF/SstPdKXpPHfdKyclBJYsLoDHPVaov4sZIzL0+37UAKD0a112wQxdOVdVtf3jdh+bTCLCRhiQ7QEmQNDfKIS5cM2O8ny8l2MFEAnKIqsTBjb6DRMnUn3cDdwnCnuMjyj1xnl9FCwvBSdEZp3LGS+cuNGN6eC/Jm4eOfVNWHmUVthFBXwwxwHJL/NkNjxmCXmr1T+NK+titbSUBBJDkwzMZvLk63zD6PyE149fgVMOLl7tjGoPIK/rCWfEZswjoooREXJN3fcFYW1+amjQ/NZH3Ocq6c2t/Io0Oj4Yy48h5zw53tzpjXq7GQTs2uRyoeshflMA5fiBK7ozW9/nfxT83K5wTA4ING3HakgqBsJ+HWIJhlyFDT3YrIm5tSJ4hW9dqAU3VfVanhyJurjI/LudMPo5gILUh9cQNXvid0oRXKi5qsLjkkPe9tS5/5Dyj2UlLF4lWfmZKvWKQnF6/ZRuV3z8LazHCuvpf+icWnKfPn4BUoLXLW30+j9sYsPfFUwwd+rqlhAXeHaydRy2y26G5xCpw7JbI4SgWsV/mIDetRbFtyKt5oEEzezRd8cn5u5B+w/+F2zecex1IxGQazJwmv0iJXp5Z9bp66puCuHubQ7XaAwVh4ThyK8iQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
